In [18]:
import os

print(os.listdir("/content"))

['.config', 'Dataset .csv', 'sample_data']

In [19]:
import pandas as pd

df = pd.read_csv("/content/Dataset .csv")

df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [ ]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:

df = pd.read_csv("/content/Dataset .csv")


df.head()

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [ ]:
print("Dataset Shape:", df.shape)

print("\nColumns:\n")
print(df.columns)

print("\nDataset Information:\n")
df.info()

Dataset Shape: (9551, 21)

Columns:

Index(['Restaurant ID', 'Restaurant Name', 'Country Code', 'City', 'Address',
       'Locality', 'Locality Verbose', 'Longitude', 'Latitude', 'Cuisines',
       'Average Cost for two', 'Currency', 'Has Table booking',
       'Has Online delivery', 'Is delivering now', 'Switch to order menu',
       'Price range', 'Aggregate rating', 'Rating color', 'Rating text',
       'Votes'],
      dtype='object')

Dataset Information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

In [ ]:
df.isnull().sum()

Restaurant ID           0
Restaurant Name         0
Country Code            0
City                    0
Address                 0
Locality                0
Locality Verbose        0
Longitude               0
Latitude                0
Cuisines                9
Average Cost for two    0
Currency                0
Has Table booking       0
Has Online delivery     0
Is delivering now       0
Switch to order menu    0
Price range             0
Aggregate rating        0
Rating color            0
Rating text             0
Votes                   0
dtype: int64

In [ ]:
for col in df.columns:

    if df[col].dtype == "object":

        df[col] = df[col].fillna(df[col].mode()[0])

    else:

        df[col] = df[col].fillna(df[col].median())

print("Missing values handled successfully.")

Missing values handled successfully.

In [ ]:
data = df[[
    "Restaurant Name",
    "City",
    "Cuisines",
    "Average Cost for two",
    "Price range",
    "Aggregate rating"
]]

data.head()

,Restaurant Name,City,Cuisines,Average Cost for two,Price range,Aggregate rating
0,Le Petit Souffle,Makati City,"French, Japanese, Desserts",1100,3,4.8
1,Izakaya Kikufuji,Makati City,Japanese,1200,3,4.5
2,Heat - Edsa Shangri-La,Mandaluyong City,"Seafood, Asian, Filipino, Indian",4000,4,4.4
3,Ooma,Mandaluyong City,"Japanese, Sushi",1500,4,4.9
4,Sambo Kojin,Mandaluyong City,"Japanese, Korean",1500,4,4.8

In [ ]:
data["Average Cost for two"] = data["Average Cost for two"].astype(str)

data["Price range"] = data["Price range"].astype(str)

/tmp/ipykernel_5894/3346754617.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Average Cost for two"] = data["Average Cost for two"].astype(str)
/tmp/ipykernel_5894/3346754617.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Price range"] = data["Price range"].astype(str)

In [ ]:
data["Features"] = (

    data["City"] + " " +

    data["Cuisines"] + " " +

    data["Price range"]

)

data.head()

/tmp/ipykernel_5894/3039622495.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Features"] = (

,Restaurant Name,City,Cuisines,Average Cost for two,Price range,Aggregate rating,Features
0,Le Petit Souffle,Makati City,"French, Japanese, Desserts",1100,3,4.8,"Makati City French, Japanese, Desserts 3"
1,Izakaya Kikufuji,Makati City,Japanese,1200,3,4.5,Makati City Japanese 3
2,Heat - Edsa Shangri-La,Mandaluyong City,"Seafood, Asian, Filipino, Indian",4000,4,4.4,"Mandaluyong City Seafood, Asian, Filipino, Ind..."
3,Ooma,Mandaluyong City,"Japanese, Sushi",1500,4,4.9,"Mandaluyong City Japanese, Sushi 4"
4,Sambo Kojin,Mandaluyong City,"Japanese, Korean",1500,4,4.8,"Mandaluyong City Japanese, Korean 4"

In [ ]:
cv = CountVectorizer()

feature_matrix = cv.fit_transform(data["Features"])

print(feature_matrix.shape)

(9551, 316)

In [ ]:
similarity = cosine_similarity(feature_matrix)

print(similarity.shape)

(9551, 9551)

In [30]:
def recommend_restaurant(name):

    if name not in data["Restaurant Name"].values:

        print("Restaurant not found.")

        return

    index = data[data["Restaurant Name"] == name].index[0]

    distances = list(enumerate(similarity[index]))

    distances = sorted(distances, key=lambda x: x[1], reverse=True)

    print("\nRecommended Restaurants\n")

    count = 0

    for i in distances[1:]:

        restaurant = data.iloc[i[0]]

        print("--------------------------------")

        print("Restaurant :", restaurant["Restaurant Name"])

        print("City :", restaurant["City"])

        print("Cuisine :", restaurant["Cuisines"])

        print("Average Cost :", restaurant["Average Cost for two"])

        print("Rating :", restaurant["Aggregate rating"])

        count += 1

        if count == 5:

            break

In [ ]:
data["Restaurant Name"].head(20)

0                             Le Petit Souffle
1                             Izakaya Kikufuji
2                       Heat - Edsa Shangri-La
3                                         Ooma
4                                  Sambo Kojin
5                                 Din Tai Fung
6                                   Buffet 101
7                                      Vikings
8     Spiral - Sofitel Philippine Plaza Manila
9                                     Locavore
10                            Silantro Fil-Mex
11             Mad Mark's Creamery & Good Eats
12                            Silantro Fil-Mex
13                                  Guevarra's
14                     Sodam Korean Restaurant
15                               Cafe Arabelle
16                    Nonna's Pasta & Pizzeria
17                                  Balay Dako
18                  Hobing Korean Dessert Cafe
19                     Wildflour Cafe + Bakery
Name: Restaurant Name, dtype: object

In [32]:
recommend_restaurant("Domino's Pizza")

Recommended Restaurants

--------------------------------
Restaurant : Flying Pie Pizzaria
City : Boise
Cuisine : Pizza
Average Cost : 25
Rating : 4.1
--------------------------------
Restaurant : Guido's Original New York Style Pizza
City : Boise
Cuisine : Pizza
Average Cost : 10
Rating : 4.3
--------------------------------
Restaurant : Mellow Mushroom
City : Columbus
Cuisine : Pizza
Average Cost : 25
Rating : 4.1
--------------------------------
Restaurant : That Baat
City : Aurangabad
Cuisine : Maharashtrian
Average Cost : 450
Rating : 3.4
--------------------------------
Restaurant : Kareem's Kabab & Biryani
City : Aurangabad
Cuisine : Mughlai
Average Cost : 650
Rating : 3.4

In [33]:
recommend_restaurant("Cafe Coffee Day")

Recommended Restaurants

--------------------------------
Restaurant : TcozY
City : Faridabad
Cuisine : Cafe
Average Cost : 1500
Rating : 0.0
--------------------------------
Restaurant : Cafe Bite
City : Faridabad
Cuisine : Cafe
Average Cost : 500
Rating : 3.2
--------------------------------
Restaurant : Cafe Coffee Day
City : Faridabad
Cuisine : Cafe
Average Cost : 450
Rating : 3.3
--------------------------------
Restaurant : The Binge Box Cafe
City : Faridabad
Cuisine : Cafe
Average Cost : 500
Rating : 3.4
--------------------------------
Restaurant : Tmos Cafe Corner
City : Faridabad
Cuisine : Cafe
Average Cost : 700
Rating : 0.0

In [34]:
print("Restaurant Recommendation System Completed Successfully.\n")

print("Summary")

print("- Dataset Loaded")

print("- Missing Values Handled")

print("- Features Combined")

print("- CountVectorizer Applied")

print("- Cosine Similarity Calculated")

print("- Content-Based Recommendation System Built")

print("- Recommendations Tested")

Restaurant Recommendation System Completed Successfully.

Summary
- Dataset Loaded
- Missing Values Handled
- Features Combined
- CountVectorizer Applied
- Cosine Similarity Calculated
- Content-Based Recommendation System Built
- Recommendations Tested